baseURL = "https://rogers.netlify.app/"
languageCode = "en-us"
title = "Roger's Blog"
theme = "noteworthy"

[params]
description = "Noteworthy is a minimalist Hugo theme, perfect for writers and bloggers."
twitter = "https://twitter.com/martins4224"
