baseURL = "https://wonderful-hopper-4c889b.netlify.app/"
languageCode = "en-us"
title = "Roger's Blog"
theme = "noteworthy"

[params]
description = "Noteworthy is a minimalist Hugo theme, perfect for writers and bloggers."
email = "g.pichok@gmail.com"
twitter = "https://twitter.com/martins4224"
